### ISSUE TITLE
Prevent some applications to disable the screensaver

### ISSUE THREAD

**Issue by vincentbernat** [vincentbernat/xssproxy#3]
Hey!

Firefox is quite abusive and disables the screen saver for any tab playing sound or displaying videos. I would like to prevent that. It would mean that xssproxy should like to firefox, pretending everything is fine, while not disabling the screen saver.

As it is not a one-line patch, I wanted to get your input before attempting that. One approach would be to have two hash tables: one for ignored apps and one for regular apps. Or one table, but we need to also store a tag as well. What do you think?

**Comment by timakro** [comment]
Hi :)

I'm no longer using the software myself and I don't want to spend the time reviewing and testing a non-trivial patch. If you want to take over maintainership of this project I will transfer the repository to your account. Naturally, I'm not demanding any long-term commitment from you; it's just that I don't like code that's not personally validated by me on my GitHub.

Also if you're using my Debian package I'm afraid I won't be able to update that. This is the only thing I packaged for Debian and it's been years, add to this that I'm now using Arch. So I suppose the Debian package would be up for adoption as well should someone step up.

**Comment by vincentbernat** [comment]
I was secretly hoping that you would say "yes, I have just added a commit doing just that". ;-) I can maintain both (I am a Debian dev).

**Comment by timakro** [comment]
I hate to disappoint you like that :P I've initiated the transfer to your account. Make xssproxy better and have fun :) Contact me again if you want take over the Debian package as well.

**Comment by timakro** [comment]
Hmpf, actually the transfer failed because your fork already occupies https://github.com/vincentbernat/xssproxy. You'll have to free that URL for me to start the transfer.

**Comment by vincentbernat** [comment]
Done. As for the Debian package, I don't really need you to take over (as long as you agree of course).

Thanks!

**Comment by timakro** [comment]
Here you go. Yeah you sure can go ahead and update the package on Debian.
